/* ================= DATA: cases, diagnostic tree, anatomy info ================= */
window.OCU_DATA = (function(){
const CASES = [
 {id:'vi-dm', titulo:'Visión doble al manejar', lesion:{R:'VI'},
  vineta:'Hombre de 62 años con diabetes tipo 2 e hipertensión de larga evolución. Desde hace 4 días ve doble al manejar: las imágenes se separan en horizontal y la separación empeora al mirar a lo lejos y hacia la derecha. Pupilas normales, sin ptosis.',
  dx:'Parálisis del VI par derecho, probablemente microvascular.',
  preguntas:[
   {q:'Explora la posición primaria y la mirada lateral. ¿Qué desviación encuentras?', opts:['Endotropia que aumenta en la mirada a la derecha','Exotropia que aumenta en la mirada a la izquierda','Hipertropia derecha que aumenta en la mirada hacia abajo','Ortotropia en todas las posiciones'], c:0, gaze:[30,0],
    fb:'El OD no pasa de la línea media al mirar a la derecha. Es una endotropia incomitante: mayor en el campo de acción del músculo parético.'},
   {q:'¿Qué tipo de diplopía describe el paciente?', opts:['Horizontal no cruzada (homónima)','Horizontal cruzada (heterónima)','Vertical','Monocular'], c:0,
    fb:'En la endotropia la imagen del ojo desviado cae en retina nasal y se proyecta hacia temporal, así que cada imagen queda del lado de su ojo. Compruébalo en «Lo que ve el paciente».'},
   {q:'¿Qué postura compensadora esperas?', opts:['Cara girada hacia la derecha','Cara girada hacia la izquierda','Cabeza inclinada hacia la izquierda','Mentón elevado'], c:0,
    fb:'Girar la cara hacia el lado del RL parético lleva los ojos hacia la izquierda, lejos del campo de acción del músculo, donde el paciente puede fusionar.'},
   {q:'¿Cuál es la conducta más apropiada?', opts:['Control de factores vasculares y vigilancia; neuroimagen si hay datos atípicos o no mejora en unas 12 semanas','Punción lumbar inmediata','Prueba de edrofonio como primer estudio','Cirugía de estrabismo en la primera semana'], c:0,
    fb:'En mayores de 50 con factores de riesgo vascular y una parálisis aislada, la causa más frecuente es isquémica y suele resolver en 8 a 12 semanas. Muchos centros hacen RM desde el inicio; es obligatoria si hay dolor atípico, otros déficits, papiledema o falta de mejoría.'}
  ]},
 {id:'iv-tce', titulo:'Diplopía vertical tras un accidente', lesion:{R:'IV'},
  vineta:'Hombre de 24 años, motociclista, con traumatismo craneoencefálico hace 3 semanas. Ve doble en vertical y las imágenes se ven inclinadas, sobre todo al bajar escaleras y al leer. En sus fotos recientes aparece con la cabeza inclinada hacia la izquierda.',
  dx:'Parálisis del IV par derecho (oblicuo superior derecho).',
  preguntas:[
   {q:'Paso 1. En posición primaria, ¿qué ojo está más alto?', opts:['El derecho','El izquierdo','Ninguno','Alternan'], c:0,
    fb:'Hipertropia derecha. El músculo parético es un depresor del OD (RI u OS) o un elevador del OI (RS u OI).'},
   {q:'Paso 2. ¿En qué mirada horizontal aumenta la hipertropia derecha?', opts:['Mirada a la izquierda','Mirada a la derecha','Igual en ambas'], c:0, gaze:[-25,0],
    fb:'Aumenta a la izquierda. Quedan dos candidatos: OS derecho (el OD está aducido) y RS izquierdo (el OI está abducido).'},
   {q:'Paso 3. ¿Con qué inclinación de la cabeza aumenta?', opts:['Inclinación hacia la derecha','Inclinación hacia la izquierda','No cambia'], c:0, tilt:25,
    fb:'Al inclinar a la derecha, el OD debe intorsionar con RS y OS. Sin OS, el RS eleva sin oposición y la hipertropia aumenta. El músculo parético es el OS derecho: IV par derecho.'},
   {q:'¿Qué torsión tiene el ojo derecho?', opts:['Extorsión','Intorsión','Ninguna'], c:0,
    fb:'El OS es el principal intorsor. Sin él, el OI extorsiona sin oposición. Se mide con doble varilla de Maddox o en el fondo de ojo (la fóvea queda baja respecto al disco).'},
   {q:'¿Por qué el IV par es tan vulnerable al traumatismo?', opts:['Es el par más largo y delgado en su trayecto intracraneal y sale por la cara dorsal del tronco, junto al borde libre del tentorio','Atraviesa el canal de Dorello','Viaja dentro del seno cavernoso junto a la carótida','Sus fibras pupilares son periféricas'], c:0,
    fb:'Es el único par que sale por la cara dorsal y se decusa por completo; su trayecto largo alrededor del mesencéfalo lo expone al golpe contra el tentorio. Por la decusación, una lesión nuclear afecta al OS contralateral.'}
  ]},
 {id:'iii-aneur', titulo:'Cefalea súbita y párpado caído', lesion:{R:'III'},
  vineta:'Mujer de 45 años con cefalea súbita e intensa desde hace 6 horas. No puede abrir el ojo derecho. Al levantarle el párpado, el ojo está desviado hacia abajo y afuera y la pupila derecha mide 6.5 mm y no reacciona a la luz.',
  dx:'Parálisis completa del III par derecho con afección pupilar: descartar aneurisma de la arteria comunicante posterior.',
  preguntas:[
   {q:'¿Qué músculos conservan su función en el ojo derecho?', opts:['Recto lateral y oblicuo superior','Recto medial y recto inferior','Recto superior y oblicuo inferior','Ninguno'], c:0,
    fb:'El RL (VI) y el OS (IV) no dependen del III. Sin oposición llevan el ojo hacia afuera y ligeramente hacia abajo, con intorsión al intentar mirar abajo.'},
   {q:'¿Qué dato orienta a una causa compresiva?', opts:['La midriasis arreactiva','La ptosis completa','La exotropia','El dolor'], c:0,
    fb:'Las fibras pupilomotoras viajan en la periferia dorsomedial del nervio. Una compresión externa las afecta temprano; la isquemia microvascular daña el centro y suele respetarlas.'},
   {q:'¿Qué causa debes descartar de inmediato?', opts:['Aneurisma de la arteria comunicante posterior','Mononeuropatía diabética','Miastenia ocular','Oftalmopatía tiroidea'], c:0,
    fb:'El III pasa entre la arteria cerebral posterior y la cerebelosa superior y corre junto a la comunicante posterior. Un aneurisma de la AComP en expansión puede romperse en horas o días. Míralo en Anatomía 3D.'},
   {q:'¿Qué estudio solicitas?', opts:['Angio-TC o angio-RM de cráneo urgente','Hemoglobina glucosilada y cita en 3 meses','Prueba del hielo','Campimetría'], c:0,
    fb:'La angio-TC es rápida y sensible para aneurismas de más de 3 a 4 mm. Si es negativa y la sospecha persiste, se hace angiografía por sustracción digital.'}
  ]},
 {id:'iii-isq', titulo:'Ptosis con pupila normal', lesion:{L:'IIIps'},
  vineta:'Hombre de 67 años con diabetes mal controlada e hipertensión. Amaneció con el párpado izquierdo caído y dolor periorbitario leve. El ojo izquierdo está abajo y afuera; ambas pupilas miden 3.5 mm y reaccionan igual.',
  dx:'Parálisis del III par izquierdo con respeto pupilar, probablemente microvascular.',
  preguntas:[
   {q:'¿Cómo se llama este patrón?', opts:['Parálisis del III con respeto pupilar','Síndrome de Horner','Oftalmoplejía internuclear','Parálisis del IV'], c:0,
    fb:'Oftalmoplejía y ptosis completas del III con pupila normal.'},
   {q:'¿Por qué la isquemia respeta la pupila?', opts:['Las fibras pupilomotoras están en la periferia, irrigadas por vasos piales, y la isquemia daña el centro del nervio','Las fibras pupilares viajan con el simpático','La pupila depende del VI','El ganglio ciliar resiste la isquemia'], c:0,
    fb:'El infarto de los vasa nervorum afecta el núcleo central del nervio. La periferia, donde van las fibras parasimpáticas, conserva su irrigación pial.'},
   {q:'¿Qué vigilas en los primeros días?', opts:['La pupila: si se dilata, estudiar compresión de inmediato','La agudeza visual','La presión intraocular','La sensibilidad corneal'], c:0,
    fb:'Hasta un porcentaje pequeño de aneurismas debuta con pupila normal. Si la pupila se afecta después, cambia el diagnóstico y requiere imagen vascular urgente.'},
   {q:'¿Qué pronóstico esperas?', opts:['Recuperación en 8 a 12 semanas en la mayoría','Parálisis permanente','Progresión a otros pares','Recuperación en 48 horas'], c:0,
    fb:'Las mononeuropatías isquémicas suelen recuperarse por completo en tres meses. Si no hay mejoría o aparecen otros signos, se estudia.'}
  ]},
 {id:'ino-em', titulo:'Visión doble al voltear rápido', lesion:{R:'INO'},
  vineta:'Mujer de 27 años con antecedente de neuritis óptica. Nota visión doble fugaz al voltear rápido hacia la izquierda. En posición primaria los ojos están alineados.',
  dx:'Oftalmoplejía internuclear derecha (fascículo longitudinal medial derecho).',
  preguntas:[
   {q:'Pide la mirada a la izquierda. ¿Qué observas?', opts:['El OD no aduce por completo y el OI tiene nistagmo en abducción','El OI no abduce','Ningún ojo pasa la línea media','El OD se eleva'], c:0, gaze:[-30,0],
    fb:'Paresia de aducción del OD y nistagmo disociado del ojo que abduce.'},
   {q:'Pide convergencia. El OD sí aduce. ¿Qué significa?', opts:['El núcleo del III y el RM están íntegros: la lesión es supranuclear, en el FLM','Parálisis parcial del III','Miopatía del recto medial','Simulación'], c:0, conv:true,
    fb:'La convergencia llega al subnúcleo del RM por una vía distinta al FLM. Si converge, el problema está en la conexión internuclear.'},
   {q:'¿Dónde está la lesión?', opts:['FLM derecho','FLM izquierdo','Núcleo del VI derecho','FRPP izquierda'], c:0,
    fb:'La INO se nombra por el ojo que no aduce: la lesión está en el FLM del mismo lado. Míralo en Anatomía 3D con la capa Tronco.'},
   {q:'¿Qué estudio y causa son más probables?', opts:['RM de encéfalo con gadolinio; esclerosis múltiple','TC simple; hemorragia','Angio-TC; aneurisma','Anticuerpos antirreceptor de acetilcolina; miastenia'], c:0,
    fb:'En personas jóvenes, sobre todo si es bilateral, la causa principal es desmielinizante. En adultos mayores con INO unilateral, el infarto del tronco es más frecuente. La miastenia puede imitar una INO: tenla en mente si fluctúa.'}
  ]},
 {id:'vi-hic', titulo:'Cefalea matutina y visión doble', syn:{k:'VI2',side:'R',sev:60},
  vineta:'Mujer de 23 años con IMC de 38. Tiene cefalea matutina desde hace 2 meses, oscurecimientos visuales transitorios y visión doble horizontal. El fondo de ojo muestra papiledema bilateral.',
  dx:'Paresia bilateral del VI par por hipertensión intracraneal (signo falso localizador).',
  preguntas:[
   {q:'¿Qué muestra la motilidad?', opts:['Limitación de la abducción de ambos ojos con endotropia','Exotropia','Hipertropia alternante','Normal'], c:0, gaze:[30,0],
    fb:'La endotropia aumenta en la mirada a ambos lados: paresia bilateral del RL.'},
   {q:'¿Por qué el VI se afecta en la hipertensión intracraneal?', opts:['Por su largo trayecto por el clivus y su ángulo sobre el ápex petroso, en el canal de Dorello, donde se estira','Porque es el más cercano al seno sagital','Porque cruza la línea media','Porque lleva fibras parasimpáticas'], c:0,
    fb:'Al desplazarse el tronco hacia abajo, el nervio se tensa donde queda fijo bajo el ligamento petroclinoideo. Míralo en Anatomía 3D.'},
   {q:'¿Cómo se llama este signo?', opts:['Signo falso localizador','Signo de Marcus Gunn','Signo de Collier','Fenómeno de Bell'], c:0,
    fb:'El déficit no indica una lesión en el VI, sino un aumento de la presión intracraneal.'},
   {q:'¿Cuál es el estudio inicial?', opts:['RM y venorresonancia; si son normales, punción lumbar con presión de apertura','Punción lumbar antes de cualquier imagen','Solo iniciar acetazolamida','Electromiografía'], c:0,
    fb:'Primero se excluyen masa y trombosis venosa; después la punción confirma la presión elevada con líquido normal.'}
  ]},
 {id:'seno', titulo:'Oftalmoplejía dolorosa', syn:{k:'CS',side:'R',sev:100},
  vineta:'Hombre de 50 años con dolor retroorbitario derecho, oftalmoplejía completa del ojo derecho, hipoestesia en la frente derecha y quemosis. La pupila derecha mide 5 mm y no reacciona.',
  dx:'Síndrome del seno cavernoso derecho.',
  preguntas:[
   {q:'¿Qué nervios están afectados?', opts:['III, IV, VI, V1 y simpático','Solo III','III y VI','II y III'], c:0,
    fb:'La oftalmoplejía completa con hipoestesia de V1 localiza al seno cavernoso o a la fisura orbitaria superior. Si además hay pérdida visual, piensa en el ápex orbitario.'},
   {q:'¿Por qué la pupila queda en posición media y arreactiva?', opts:['Se lesionan a la vez el parasimpático del III y el simpático pericarotídeo','Solo se lesiona el parasimpático','Es una midriasis farmacológica','Por lesión del nervio óptico'], c:0,
    fb:'Sin parasimpático ni simpático, el iris queda sin tono en ninguna dirección: pupila media y fija.'},
   {q:'¿Qué nervio viaja dentro del seno, junto a la carótida, y no en su pared lateral?', opts:['VI','III','IV','V2'], c:0,
    fb:'III, IV, V1 y V2 corren en la pared lateral. El VI va libre dentro del seno, lateral a la carótida; por eso suele ser el primero en afectarse en aneurismas cavernosos.'},
   {q:'¿Qué causas consideras?', opts:['Fístula carótido-cavernosa, trombosis séptica, tumores y síndrome de Tolosa-Hunt','Esclerosis múltiple','Miastenia','Encefalopatía de Wernicke'], c:0,
    fb:'La quemosis y la proptosis orientan a fístula o trombosis. El dolor que responde a esteroides con RM compatible sugiere Tolosa-Hunt, un diagnóstico de exclusión.'}
  ]},
 {id:'uno-medio', titulo:'No puede mirar a la derecha', syn:{k:'OAH',side:'R',sev:100},
  vineta:'Hombre de 34 años con esclerosis múltiple. Refiere visión doble y dificultad para mirar a la derecha.',
  dx:'Síndrome del uno y medio derecho (núcleo del VI o FRPP derecha más FLM derecho).',
  preguntas:[
   {q:'¿Qué único movimiento horizontal conserva?', opts:['La abducción del OI','La aducción del OD','La abducción del OD','Ninguno'], c:0, gaze:[-30,0],
    fb:'Hacia la derecha no se mueve ningún ojo (el «uno»). Hacia la izquierda solo abduce el OI, con nistagmo (el «medio»).'},
   {q:'¿Dónde está la lesión?', opts:['FRPP o núcleo del VI derecho, más FLM derecho','FLM bilateral','Núcleo del III izquierdo','VI periférico derecho'], c:0,
    fb:'El núcleo del VI contiene motoneuronas del RL e interneuronas que cruzan al FLM contralateral. Su lesión causa parálisis de la mirada ipsilateral; sumada al FLM ipsilateral, se pierde también la aducción de ese ojo.'},
   {q:'¿Qué movimiento confirma que el RM derecho está íntegro?', opts:['La convergencia','La elevación','La pupila','El reflejo corneal'], c:0, conv:true,
    fb:'Igual que en la INO, la convergencia se conserva porque usa otra vía al subnúcleo del recto medial.'}
  ]},
 {id:'horner', titulo:'Párpado algo caído y pupila pequeña', lesion:{L:'HOR'},
  vineta:'Mujer de 52 años, fumadora, con dolor en el hombro y el brazo izquierdos. Su familia notó el párpado izquierdo algo caído. La motilidad ocular es normal.',
  dx:'Síndrome de Horner izquierdo: descartar tumor del vértice pulmonar (Pancoast).',
  preguntas:[
   {q:'¿Cuál pupila es la anormal?', opts:['La izquierda, pequeña (miosis)','La derecha, grande','Ambas','Ninguna'], c:0,
    fb:'Si la anisocoria aumenta en la oscuridad, la pupila pequeña es la que no dilata: falla simpática.'},
   {q:'¿Por qué la ptosis es leve?', opts:['Se pierde el músculo de Müller (simpático), no el elevador','Es una lesión parcial del III','Es miastenia','Es dermatocalasia'], c:0,
    fb:'El músculo de Müller aporta 1 a 2 mm de elevación. El elevador, inervado por el III, sigue funcionando.'},
   {q:'¿Qué estudio pides?', opts:['Imagen del vértice pulmonar (radiografía o TC de tórax)','Angio-TC por aneurisma de la AComP','RM por lesión del FLM','Punción lumbar'], c:0,
    fb:'Con dolor en hombro y brazo en una fumadora, el Horner preganglionar obliga a buscar un tumor de Pancoast. Un Horner doloroso de inicio agudo obliga a descartar disección carotídea.'}
  ]}
];

/* ---------- diplopia decision tree ---------- */
const TREE = {
 root:{q:'¿La visión doble desaparece al tapar cualquiera de los dos ojos?', opts:[['Sí, desaparece: es binocular','pupil'],['No, persiste con un ojo tapado','mono']]},
 mono:{dx:'Diplopía monocular', text:'La causa es ocular, no neurológica: error refractivo o astigmatismo, catarata, alteraciones de la córnea, del cristalino o de la retina. Si mejora con el agujero estenopeico, el origen es óptico.'},
 pupil:{q:'¿Hay anisocoria?', opts:[['Sí, midriasis del lado afectado','iiicomp'],['Sí, miosis con ptosis leve','horner'],['No, pupilas iguales y reactivas','ptosis']]},
 iiicomp:{dx:'III par con afección pupilar', text:'Ojo abajo y afuera, ptosis y midriasis arreactiva. La compresión afecta primero las fibras pupilares periféricas: descarta aneurisma de la AComP con angio-TC urgente.', load:{les:{R:'III'}}},
 horner:{dx:'Síndrome de Horner', text:'Ptosis leve (Müller), miosis y anisocoria mayor en la oscuridad; la motilidad es normal. Si hay diplopía, busca otra lesión asociada: el seno cavernoso afecta a la vez al simpático y a los pares oculomotores.', load:{les:{L:'HOR'}}},
 ptosis:{q:'¿Hay ptosis?', opts:[['Sí, completa, con el ojo abajo y afuera','iiiisq'],['Sí, variable y peor al final del día','mg'],['No','dir']]},
 iiiisq:{dx:'III par con respeto pupilar', text:'Patrón típico de mononeuropatía isquémica (diabetes, hipertensión). Vigila la pupila y espera recuperación en 8 a 12 semanas; estudia si aparece midriasis, otros déficits o no mejora.', load:{les:{R:'IIIps'}}},
 mg:{dx:'Miastenia gravis ocular', text:'Ptosis y diplopía fluctuantes y fatigables que imitan cualquier patrón nervioso, con pupila siempre normal. Apoyan el diagnóstico la prueba del hielo, la fatiga en mirada sostenida hacia arriba y el signo de Cogan; se confirma con anticuerpos anti-AChR o anti-MuSK y con electromiografía de fibra única. Busca timoma.'},
 dir:{q:'¿Cómo se separan las imágenes?', opts:[['En horizontal (lado a lado)','horiz'],['En vertical o inclinadas','vert']]},
 horiz:{q:'¿Qué limitación encuentras en las ducciones?', opts:[['Un ojo no abduce','vi'],['Un ojo no aduce en la mirada lateral, pero sí converge','ino'],['Un ojo no aduce y el otro tampoco abduce hacia ese lado','oah'],['Ducciones completas','foria']]},
 vi:{q:'¿Uno o ambos ojos?', opts:[['Uno','vi1'],['Ambos','vi2']]},
 vi1:{dx:'Parálisis del VI par', text:'Endotropia que aumenta hacia el lado del RL parético y de lejos; cara girada hacia ese lado. En mayores de 50 con factores vasculares, la causa más común es isquémica.', load:{les:{R:'VI'}}},
 vi2:{dx:'Paresia bilateral del VI', text:'Piensa en hipertensión intracraneal (signo falso localizador), lesiones del clivus, meningitis o encefalopatía de Wernicke. Revisa el fondo de ojo.', load:{syn:{k:'VI2',side:'R',sev:70}}},
 ino:{dx:'Oftalmoplejía internuclear', text:'Lesión del FLM del lado del ojo que no aduce; nistagmo del ojo que abduce y convergencia conservada. Joven: esclerosis múltiple. Adulto mayor: infarto del tronco.', load:{les:{R:'INO'}}},
 oah:{dx:'Síndrome del uno y medio', text:'Parálisis de la mirada hacia un lado más INO del mismo lado: solo abduce el ojo contralateral. Lesión del núcleo del VI o FRPP más FLM ipsilaterales.', load:{syn:{k:'OAH',side:'R',sev:100}}},
 foria:{dx:'Desviación comitante', text:'Con ducciones completas y desviación igual en todas las posiciones, piensa en una foria descompensada, insuficiencia de convergencia o de divergencia. Si hay signos de tronco, considera una desviación oblicua (skew).'},
 vert:{q:'¿Cómo se comporta la hipertropia?', opts:[['Cambia con la mirada y con la inclinación de la cabeza','parks'],['Hay vértigo, ataxia u otros signos de tronco y no sigue el patrón de un músculo','skew'],['Hay limitación mecánica: fractura del piso orbitario u oftalmopatía tiroidea','restr']]},
 parks:{dx:'Parálisis de un músculo cicloverical', text:'Usa los tres pasos de Parks-Bielschowsky para identificar el músculo. La causa más frecuente de diplopía vertical aislada es la parálisis del IV.', go:'parks', load:{les:{R:'IV'}}},
 skew:{dx:'Desviación oblicua (skew)', text:'Desviación vertical supranuclear por lesión de la vía otolítica (tronco o cerebelo). Suele cambiar con la posición supina y forma parte del HINTS en el síndrome vestibular agudo: si está presente, sugiere causa central.'},
 restr:{dx:'Estrabismo restrictivo', text:'La prueba de ducción forzada es positiva. En la oftalmopatía tiroidea el recto inferior engrosado limita la elevación; en la fractura del piso orbitario puede atraparse el recto inferior. Solicita TC de órbitas.'}
};

/* ---------- anatomy info ---------- */
const INFO = {
 SR:{n:'Recto superior',t:'Músculo extraocular',o:'Anillo de Zinn, porción superior',i:'Esclera, 7.7 mm del limbo',v:'III, división superior (el subnúcleo es contralateral)',a:'Elevación; secundaria intorsión; terciaria aducción. Eleva mejor en abducción (plano a 23°).',p:'Las fibras del subnúcleo del RS se decusan dentro del complejo del III: una lesión nuclear debilita el RS contralateral.'},
 IR:{n:'Recto inferior',t:'Músculo extraocular',o:'Anillo de Zinn, porción inferior',i:'Esclera, 6.5 mm del limbo',v:'III, división inferior',a:'Depresión; secundaria extorsión; terciaria aducción. Deprime mejor en abducción.',p:'Es el músculo más afectado en la oftalmopatía tiroidea y el que puede quedar atrapado en la fractura del piso orbitario.'},
 MR:{n:'Recto medial',t:'Músculo extraocular',o:'Anillo de Zinn, porción medial',i:'Esclera, 5.5 mm del limbo (el más cercano)',v:'III, división inferior',a:'Aducción pura.',p:'En la INO no aduce en la mirada lateral pero sí en convergencia: la vía de la convergencia no pasa por el FLM.'},
 LR:{n:'Recto lateral',t:'Músculo extraocular',o:'Anillo de Zinn (dos cabezas que puentean la fisura orbitaria superior)',i:'Esclera, 6.9 mm del limbo',v:'VI par (abducens)',a:'Abducción pura.',p:'RL6: el único músculo del VI. Su parálisis da endotropia que empeora de lejos y hacia el lado lesionado.'},
 SO:{n:'Oblicuo superior',t:'Músculo extraocular',o:'Cuerpo del esfenoides, superomedial al conducto óptico',i:'Esclera posterior, cuadrante superotemporal, tras pasar por la tróclea',v:'IV par (troclear), por su cara superior',a:'Intorsión; secundaria depresión; terciaria abducción. Deprime mejor en aducción (plano a 51°).',p:'OS4. Su parálisis da hipertropia que aumenta en la mirada contralateral, hacia abajo y con la inclinación hacia el lado lesionado.'},
 IO:{n:'Oblicuo inferior',t:'Músculo extraocular',o:'Piso orbitario anteromedial (maxilar), junto a la fosa lagrimal',i:'Esclera posterior, cuadrante inferotemporal, cerca de la mácula',v:'III, división inferior',a:'Extorsión; secundaria elevación; terciaria abducción. Eleva mejor en aducción.',p:'Es el único músculo extraocular que no nace en el ápex. Su nervio lleva la raíz motora del ganglio ciliar.'},
 LPS:{n:'Elevador del párpado superior',t:'Músculo palpebral',o:'Ala menor del esfenoides, sobre el anillo de Zinn',i:'Aponeurosis en la placa tarsal y la piel del párpado superior',v:'III, división superior (núcleo caudal central, único y bilateral)',a:'Eleva el párpado superior.',p:'Como el núcleo caudal central es único, una lesión nuclear del III produce ptosis bilateral.'},
 globe:{n:'Globo ocular',t:'Órgano',o:'—',i:'—',v:'—',a:'Gira alrededor de su centro; el eje visual pasa por la fóvea.',p:'Mide unos 24 mm. La marca roja a las 12 h del limbo permite ver la intorsión y la extorsión.'},
 optic:{n:'Nervio óptico (II)',t:'Nervio craneal sensorial',o:'Células ganglionares de la retina',i:'Quiasma óptico',v:'—',a:'Conduce la información visual.',p:'Pasa por el conducto óptico dentro del anillo de Zinn. Su afección junto con III, IV y VI localiza en el ápex orbitario.'},
 annulus:{n:'Anillo de Zinn',t:'Tendón común',o:'—',i:'—',v:'—',a:'Origen de los cuatro rectos.',p:'Por dentro pasan II, III (ambas divisiones), VI y el nasociliar. Por fuera, en la fisura orbitaria superior, pasan IV, frontal y lagrimal.'},
 trochlea:{n:'Tróclea',t:'Polea fibrocartilaginosa',o:'Fosa troclear del frontal',i:'—',v:'—',a:'Cambia la dirección de tracción del oblicuo superior.',p:'Desde la tróclea el tendón del OS va hacia atrás y afuera: por eso su acción depende de la posición horizontal del ojo.'},
 sof:{n:'Fisura orbitaria superior',t:'Agujero de la base',o:'—',i:'—',v:'—',a:'Comunica la fosa craneal media con la órbita.',p:'Su síndrome afecta III, IV, VI y V1 sin pérdida visual; con pérdida visual es síndrome del ápex orbitario.'},
 bone:{n:'Órbita ósea',t:'Hueso',o:'—',i:'—',v:'—',a:'Pirámide de unos 45 mm de profundidad.',p:'Las paredes mediales son casi paralelas y las laterales divergen unos 90° entre sí; el eje de la órbita diverge unos 23° del eje visual.'},
 III:{n:'III par · tronco',t:'Nervio motor ocular común',o:'Complejo nuclear del III en el mesencéfalo, a la altura del colículo superior',i:'RS, elevador, RM, RI, OI y esfínter del iris (vía ganglio ciliar)',v:'—',a:'Sale por la fosa interpeduncular, pasa entre la ACP y la ACS, corre junto a la AComP y entra a la pared lateral del seno cavernoso.',p:'Las fibras pupilares van en la periferia: la compresión (aneurisma, herniación uncal) dilata la pupila; la isquemia suele respetarla.'},
 IIIsup:{n:'III par · división superior',t:'Rama',o:'División en el seno cavernoso anterior o la fisura orbitaria superior',i:'Recto superior y elevador del párpado',v:'—',a:'Entra por la cara ocular del RS y lo atraviesa hasta el elevador.',p:'Su lesión aislada da ptosis y déficit de elevación.'},
 IIIinf:{n:'III par · división inferior',t:'Rama',o:'División en el seno cavernoso anterior o la fisura orbitaria superior',i:'Recto medial, recto inferior, oblicuo inferior y raíz motora del ganglio ciliar',v:'—',a:'Corre bajo el nervio óptico y se ramifica en el cono muscular.',p:'Su lesión da exotropia, déficit de aducción y depresión y midriasis, con párpado normal.'},
 cil:{n:'Ganglio ciliar',t:'Ganglio parasimpático',o:'Raíz motora del nervio al oblicuo inferior',i:'Nervios ciliares cortos al esfínter del iris y al músculo ciliar',v:'—',a:'Relevo de la vía pupilar y de la acomodación.',p:'Su daño produce pupila tónica de Adie: reacción lenta a la luz y mejor respuesta a la convergencia.'},
 IV:{n:'IV par (troclear)',t:'Nervio craneal motor',o:'Núcleo del IV contralateral, a la altura del colículo inferior',i:'Oblicuo superior, por su cara orbitaria',v:'—',a:'Sale por la cara dorsal, rodea el mesencéfalo, corre en la pared lateral del seno cavernoso bajo el III y entra a la órbita por fuera del anillo de Zinn.',p:'Es el más delgado, el de trayecto intracraneal más largo y el único que se decusa por completo y sale dorsal.'},
 VI:{n:'VI par (abducens)',t:'Nervio craneal motor',o:'Núcleo del VI en el piso del IV ventrículo (bajo el colículo facial)',i:'Recto lateral, por su cara ocular',v:'—',a:'Sale en la unión bulboprotuberancial, asciende por el clivus, pasa por el canal de Dorello y cruza el seno cavernoso libre, lateral a la carótida.',p:'Por su largo trayecto se afecta como falso localizador en la hipertensión intracraneal.'},
 dorello:{n:'Canal de Dorello',t:'Referencia anatómica',o:'—',i:'—',v:'—',a:'Espacio bajo el ligamento petroclinoideo (de Gruber) por donde el VI cruza el ápex petroso.',p:'Aquí el VI se angula y se estira cuando aumenta la presión intracraneal.'},
 MLF:{n:'Fascículo longitudinal medial',t:'Vía internuclear',o:'Interneuronas del núcleo del VI contralateral',i:'Subnúcleo del recto medial en el complejo del III',v:'—',a:'Coordina la mirada horizontal conjugada: cuando el RL de un ojo abduce, el RM del otro aduce.',p:'Su lesión produce la oftalmoplejía internuclear del lado lesionado.'},
 n3nuc:{n:'Complejo nuclear del III',t:'Núcleo motor',o:'Mesencéfalo, ventral al acueducto, a la altura del colículo superior',i:'—',v:'—',a:'Subnúcleos del RM, RI y OI ipsilaterales, del RS contralateral y núcleo caudal central (elevadores, bilateral).',p:'Una lesión nuclear da ptosis bilateral y debilidad del RS contralateral.'},
 ew:{n:'Núcleo de Edinger-Westphal',t:'Núcleo parasimpático',o:'Dorsal al complejo del III',i:'Ganglio ciliar',v:'—',a:'Miosis y acomodación.',p:'Recibe la vía pretectal del reflejo fotomotor de ambos lados.'},
 n4nuc:{n:'Núcleo del IV',t:'Núcleo motor',o:'Mesencéfalo, a la altura del colículo inferior',i:'Oblicuo superior del lado opuesto',v:'—',a:'Sus fibras se decusan en el velo medular superior.',p:'El OS derecho depende del núcleo del IV izquierdo.'},
 n6nuc:{n:'Núcleo del VI',t:'Núcleo motor y centro de la mirada',o:'Protuberancia dorsal, rodeado por la rodilla del facial',i:'RL ipsilateral y, por interneuronas y el FLM, el RM contralateral',v:'—',a:'Genera la mirada horizontal conjugada.',p:'Su lesión no da una parálisis del VI sino una parálisis de la mirada hacia ese lado.'},
 pprf:{n:'Formación reticular pontina paramediana',t:'Centro premotor',o:'Protuberancia',i:'Núcleo del VI ipsilateral',v:'—',a:'Genera los movimientos sacádicos horizontales.',p:'FRPP más FLM ipsilaterales: síndrome del uno y medio.'},
 brainstem:{n:'Tronco encefálico',t:'Sistema nervioso central',o:'—',i:'—',v:'—',a:'Mesencéfalo (III y IV), protuberancia (VI) y bulbo.',p:'Síndromes con pares oculomotores: Weber (III + hemiparesia contralateral), Benedikt (III + temblor), Millard-Gubler (VI + VII + hemiparesia).'},
 ica:{n:'Arteria carótida interna',t:'Arteria',o:'Carótida común',i:'Cerebral media y anterior',v:'—',a:'Forma el sifón carotídeo dentro del seno cavernoso.',p:'Su plexo simpático lleva la vía pupilodilatadora: la disección carotídea causa Horner doloroso.'},
 pcom:{n:'Arteria comunicante posterior',t:'Arteria',o:'Carótida interna supraclinoidea',i:'Arteria cerebral posterior',v:'—',a:'Une la circulación anterior y la posterior.',p:'Un aneurisma en su origen comprime el III: parálisis del III con midriasis.'},
 pca:{n:'Arteria cerebral posterior',t:'Arteria',o:'Bifurcación basilar',i:'Lóbulo occipital',v:'—',a:'El III pasa entre ella y la cerebelosa superior.',p:'Referencia clásica del trayecto cisternal del III.'},
 sca:{n:'Arteria cerebelosa superior',t:'Arteria',o:'Basilar distal',i:'Cerebelo superior',v:'—',a:'Corre bajo el III.',p:'El III queda en la pinza entre ACP y ACS.'},
 basilar:{n:'Arteria basilar',t:'Arteria',o:'Unión de las vertebrales',i:'Cerebrales posteriores',v:'—',a:'Recorre la cara ventral de la protuberancia.',p:'Los aneurismas de la punta basilar pueden comprimir el III en la fosa interpeduncular.'},
 cs:{n:'Seno cavernoso',t:'Seno venoso dural',o:'—',i:'—',v:'—',a:'A cada lado de la silla turca. En su pared lateral: III, IV, V1 y V2. Dentro: carótida interna y VI.',p:'Síndrome: oftalmoplejía dolorosa, hipoestesia de V1, Horner y pupila media fija.'},
 symp:{n:'Plexo simpático pericarotídeo',t:'Vía simpática',o:'Ganglio cervical superior',i:'Dilatador del iris y músculo de Müller',v:'—',a:'Asciende sobre la carótida interna; en el seno cavernoso se une brevemente al VI y luego al nasociliar.',p:'Su lesión da el síndrome de Horner: ptosis leve, miosis y anhidrosis variable.'},
 aneur:{n:'Aneurisma de la AComP',t:'Lesión',o:'—',i:'—',v:'—',a:'Dilatación sacular en la unión de la carótida con la comunicante posterior.',p:'Comprime la periferia del III: parálisis dolorosa con midriasis. Es una urgencia.'}
};
return {CASES, TREE, INFO};
})();
